site_name: Sistema de Gest찾o de Lanchonete

nav:
  - Home: index.md
  - Requisitos: requisitos.md
  - Diagrama de Casos de Uso: diagrama_caso_uso.md
  - Prot처tipos Figma: prototipos_figma.md
  - Conclus찾o: conclusao.md
  - C처digos do Sistema: codigo_fonte.md